from datetime import date
from seasons import display_mins

"""
file: test_seasons.py
Description:
    Testing the correctness of the output generated by the function when the input date is the current date.

"""


def test_seasons():
    assert display_mins(date.today()) == "Zero minutes"
